a=float(input("enter first number :"))
b=float(input("enter second number :"))
print("addition :",a+b)
print("subtraction :",a-b)
print("multiplication :",a*b)
print("division :",a/b)
print("modulus :",a%b)
print("exponentiation:",a**b)
print("floor division :",a//b)